# Generated by Django 5.2.18 on 2026-10-09 17:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('PROFILE_VIEW_OWN', 'View own profile'), ('PROFILE_UPDATE_OWN', 'Update own profile'), ('USER_VIEW', 'View users'), ('USER_CREATE', 'Create users'), ('USER_UPDATE', 'Update users'), ('USER_DEACTIVATE', 'Deactivate users'), ('ROLE_MANAGE', 'Manage roles'), ('CONTENT_VIEW', 'View content'), ('CONTENT_SEARCH', 'Search content'), ('CONTENT_CREATE', 'Create content'), ('CONTENT_UPDATE', 'Update content'), ('CONTENT_ARCHIVE', 'Archive content'), ('CONTENT_PUBLISH', 'Publish content'), ('VERSION_VIEW', 'View content versions'), ('VERSION_CREATE', 'Create content versions'), ('VERSION_PUBLISH', 'Publish content versions'), ('PROGRAM_VIEW', 'View programs'), ('PROGRAM_CREATE', 'Create programs'), ('PROGRAM_UPDATE', 'Update programs'), ('ASSIGNMENT_MANAGE', 'Manage content assignments'), ('ACCESS_GRANT', 'Grant content access'), ('ACCESS_REVOKE', 'Revoke content access'), ('SECURE_DELIVERY', 'Use secure content delivery'), ('WATERMARK_CONSUME', 'Consume watermarked content'), ('ACTIVITY_VIEW_OWN', 'View own activity'), ('ACTIVITY_VIEW_ORGANIZATION', 'View organization activity'), ('AUDIT_VIEW_ORGANIZATION', 'View organization audit records'), ('SECURITY_EVENT_VIEW_ORGANIZATION', 'View organization security events'), ('REPORT_VIEW_ASSIGNED', 'View reports for assigned resources'), ('REPORT_VIEW_ORGANIZATION', 'View organization reports'), ('ANALYTICS_VIEW_ASSIGNED', 'View analytics for assigned resources'), ('ANALYTICS_VIEW_ORGANIZATION', 'View organization analytics'), ('CONFIGURATION_MANAGE', 'Manage organization configuration')], max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_system_role', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='identity.organization')),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_permissions', to='identity.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='identity.role')),
            ],
            options={
                'db_table': 'role_permissions',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', through='identity.RolePermission', to='identity.permission'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_roles', to='identity.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_roles', to='identity.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_roles',
            },
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_role_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_role_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('organization', 'user', 'role'), name='unique_user_role_per_organization'),
        ),
    ]
