# Generated by Django 5.2.18 on 2026-10-09 18:56

from django.db import migrations, models


def add_version_archive_permission(apps, schema_editor):
    database = schema_editor.connection.alias
    Permission = apps.get_model("identity", "Permission")
    Role = apps.get_model("identity", "Role")
    RolePermission = apps.get_model("identity", "RolePermission")
    permission, _ = Permission.objects.using(database).get_or_create(
        code="VERSION_ARCHIVE",
        defaults={"name": "Archive content versions"},
    )
    roles = Role.objects.using(database).filter(
        is_system_role=True,
        code__in=["administrator", "content_manager"],
    )
    for role in roles:
        RolePermission.objects.using(database).get_or_create(
            role=role,
            permission=permission,
        )


def remove_version_archive_permission(apps, schema_editor):
    database = schema_editor.connection.alias
    Permission = apps.get_model("identity", "Permission")
    Permission.objects.using(database).filter(code="VERSION_ARCHIVE").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_permission_role_rolepermission_role_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(choices=[('PROFILE_VIEW_OWN', 'View own profile'), ('PROFILE_UPDATE_OWN', 'Update own profile'), ('USER_VIEW', 'View users'), ('USER_CREATE', 'Create users'), ('USER_UPDATE', 'Update users'), ('USER_DEACTIVATE', 'Deactivate users'), ('ROLE_MANAGE', 'Manage roles'), ('CONTENT_VIEW', 'View content'), ('CONTENT_SEARCH', 'Search content'), ('CONTENT_CREATE', 'Create content'), ('CONTENT_UPDATE', 'Update content'), ('CONTENT_ARCHIVE', 'Archive content'), ('CONTENT_PUBLISH', 'Publish content'), ('VERSION_VIEW', 'View content versions'), ('VERSION_CREATE', 'Create content versions'), ('VERSION_PUBLISH', 'Publish content versions'), ('VERSION_ARCHIVE', 'Archive content versions'), ('PROGRAM_VIEW', 'View programs'), ('PROGRAM_CREATE', 'Create programs'), ('PROGRAM_UPDATE', 'Update programs'), ('ASSIGNMENT_MANAGE', 'Manage content assignments'), ('ACCESS_GRANT', 'Grant content access'), ('ACCESS_REVOKE', 'Revoke content access'), ('SECURE_DELIVERY', 'Use secure content delivery'), ('WATERMARK_CONSUME', 'Consume watermarked content'), ('ACTIVITY_VIEW_OWN', 'View own activity'), ('ACTIVITY_VIEW_ORGANIZATION', 'View organization activity'), ('AUDIT_VIEW_ORGANIZATION', 'View organization audit records'), ('SECURITY_EVENT_VIEW_ORGANIZATION', 'View organization security events'), ('REPORT_VIEW_ASSIGNED', 'View reports for assigned resources'), ('REPORT_VIEW_ORGANIZATION', 'View organization reports'), ('ANALYTICS_VIEW_ASSIGNED', 'View analytics for assigned resources'), ('ANALYTICS_VIEW_ORGANIZATION', 'View organization analytics'), ('CONFIGURATION_MANAGE', 'Manage organization configuration')], max_length=64, unique=True),
        ),
        migrations.RunPython(
            add_version_archive_permission,
            remove_version_archive_permission,
        ),
    ]
