# Generated by Django 5.2.18 on 2026-10-09 18:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_permission_role_rolepermission_role_permissions_and_more'),
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('storage_key', models.CharField(max_length=512)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField()),
                ('checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='knowledge.content')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_content_versions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_versions', to='identity.organization')),
            ],
            options={
                'db_table': 'content_versions',
                'ordering': ['content_id', 'version_number'],
            },
        ),
        migrations.RenameField(
            model_name='content',
            old_name='current_version_id',
            new_name='current_version',
        ),
        migrations.AlterField(
            model_name='content',
            name='current_version',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='current_for_contents',
                to='knowledge.contentversion',
            ),
        ),
        migrations.AddIndex(
            model_name='contentversion',
            index=models.Index(fields=['organization', 'content'], name='cntver_org_content_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentversion',
            constraint=models.UniqueConstraint(fields=('organization', 'content', 'version_number'), name='unique_version_number_per_content'),
        ),
        migrations.AddConstraint(
            model_name='contentversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gt', 0)), name='content_version_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='contentversion',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'PUBLISHED', 'ARCHIVED'])), name='content_version_status_valid'),
        ),
    ]
