# Generated by Django 5.2.18 on 2026-10-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_remove_content_current_version_id_contentversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentversion',
            name='version_notes',
            field=models.TextField(blank=True),
        ),
    ]
