# Generated by Django 5.2.18 on 2026-10-09 12:20

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0001_initial'),
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationRateLimitCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_type', models.CharField(choices=[('ACCOUNT', 'Account'), ('SOURCE_IP', 'Source IP')], max_length=20)),
                ('key_hash', models.CharField(max_length=64)),
                ('failure_timestamps', models.JSONField(default=list)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'authentication_rate_limit_counters',
            },
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Information'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='securityevent',
            constraint=models.CheckConstraint(condition=models.Q(('severity__in', ['INFO', 'LOW', 'MEDIUM', 'HIGH'])), name='security_event_severity_valid'),
        ),
        migrations.AddConstraint(
            model_name='authenticationratelimitcounter',
            constraint=models.UniqueConstraint(fields=('key_type', 'key_hash'), name='unique_auth_rate_limit_key'),
        ),
        migrations.AddConstraint(
            model_name='authenticationratelimitcounter',
            constraint=models.CheckConstraint(condition=models.Q(('key_type__in', ['ACCOUNT', 'SOURCE_IP'])), name='auth_rate_limit_key_type_valid'),
        ),
    ]
