# Generated by Django 5.2.18 on 2026-10-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0002_authenticationratelimitcounter_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='authenticationratelimitcounter',
            index=models.Index(fields=['updated_at'], name='auth_rate_limit_updated_idx'),
        ),
    ]
