# Generated by Django 5.2.18 on 2026-10-09 17:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0003_authenticationratelimitcounter_auth_rate_limit_updated_idx'),
        ('identity', '0002_permission_role_rolepermission_role_permissions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CONTENT_ARCHIVED', 'Content archived')], max_length=100)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.UUIDField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_records', to='identity.organization')),
            ],
            options={
                'db_table': 'audit_records',
                'indexes': [models.Index(fields=['organization', 'occurred_at'], name='audit_org_time_idx'), models.Index(fields=['organization', 'resource_type', 'resource_id'], name='audit_org_resource_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('action__in', ['CONTENT_ARCHIVED'])), name='audit_action_valid')],
            },
        ),
    ]
