# Generated by Django 5.2.18 on 2026-10-09 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0004_auditrecord'),
        ('identity', '0002_permission_role_rolepermission_role_permissions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='auditrecord',
            name='audit_action_valid',
        ),
        migrations.AlterField(
            model_name='auditrecord',
            name='action',
            field=models.CharField(choices=[('CONTENT_ARCHIVED', 'Content archived'), ('CONTENT_VERSION_PUBLISHED', 'Content version published')], max_length=100),
        ),
        migrations.AddConstraint(
            model_name='auditrecord',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['CONTENT_ARCHIVED', 'CONTENT_VERSION_PUBLISHED'])), name='audit_action_valid'),
        ),
    ]
