# Generated by Django 5.2.18 on 2026-10-09 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0005_remove_auditrecord_audit_action_valid_and_more'),
        ('identity', '0003_alter_permission_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='auditrecord',
            name='audit_action_valid',
        ),
        migrations.AlterField(
            model_name='auditrecord',
            name='action',
            field=models.CharField(choices=[('CONTENT_ARCHIVED', 'Content archived'), ('CONTENT_VERSION_PUBLISHED', 'Content version published'), ('CONTENT_VERSION_ARCHIVED', 'Content version archived')], max_length=100),
        ),
        migrations.AddConstraint(
            model_name='auditrecord',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['CONTENT_ARCHIVED', 'CONTENT_VERSION_PUBLISHED', 'CONTENT_VERSION_ARCHIVED'])), name='audit_action_valid'),
        ),
    ]
